export { Table } from "./table"
export { TableBody } from "./table-body"
export { TableHeader } from "./table-header"
export { TableHead } from "./table-head"
export { TableRow } from "./table-row"
export { TableCell } from "./table-cell"
export { TableCaption } from "./table-caption"